name: LineageOS 16 CI

on:
  workflow_dispatch:
jobs:
  build:
    name: LineageOS Build CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - name: Check Out
      uses: actions/checkout@v7
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
    - name: Installing JDK 7 + Build Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex axel g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2_amd64.deb && sudo dpkg -i libtinfo5_6.3-2_amd64.deb && rm -f libtinfo5_6.3-2_amd64.deb
        wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.3-2_amd64.deb && sudo dpkg -i libncurses5_6.3-2_amd64.deb && rm -f libncurses5_6.3-2_amd64.deb
        cd /usr/local/src
        sudo wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        sudo tar xvf Python-2.7.18.tgz
        cd Python-2.7.18
        sudo ./configure --enable-optimizations
        sudo make altinstall
        sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python2
        sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python    
    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Syncing LineageOS sources
      run: |
        mkdir ~/lineage
        cd ~/lineage
        mkdir ~/.bin
        curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        python3 ~/.bin/repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-16.0
        curl --create-dirs -L -o .repo/local_manifests/j3y17lte.xml -O -L https://raw.githubusercontent.com/notnoelchannel2/j3xlte_manifest/refs/heads/main/j3y17lte.xml
        sudo git clone --depth 1 --branch android-8.1.0_r80 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 /opt/toolchains/aarch64-linux-android-4.9/
        git lfs install
        python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
    - name: Building LineageOS
      run: |
        OLDPATH=$PATH
        OLDJAVAHOME=$JAVA_HOME
        export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
        export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
        cd ~/lineage/kernel/samsung/exynos7570
        make mrproper
        cd ~/lineage
        rm -rf ~/lineage/.repo
        rm -rf external/chromium-webview/
        git clone https://github.com/LineageOS/android_external_chromium-webview external/chromium-webview/
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        export ARCH=arm64
        export CROSS_COMPILE=/opt/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-
        export KBUILD_BUILD_USER=notnoelchannel
        export KBUILD_BUILD_HOST=unlegacy-devices
        export ANDROID_MAJOR_VERSION=p
        python -V
        rm -rf out/target/product/j3y17lte/recovery.img
        rm -rf out/target/product/j3y17lte/obj/RECOVERY
        lunch lineage_j3y17lte-eng
        make -j$(nproc --all) otapackage
        export PATH=$OLDPATH
        export JAVA_HOME=$OLDJAVAHOME
    - name: Uploading LineageOS builds
      uses: actions/upload-artifact@v5
      with:
        name: lineage
        path: /home/runner/lineage/out/target/product/j3y17lte/*.zip
